### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Wolverine971** [learn-anything/chrome-extensions#25]
Hey I think your pesticide link is broken.
[Pesticide](http://pesticide.io/) - Quickly debug CSS layout issues by toggling different colored outlines on every element.

I think this should be the right one https://chrome.google.com/webstore/detail/pesticide-for-chrome/bakpbgckdnepkmkeaiomhmfcnejndkbi/related

**Comment by nikivdev** [comment]
Correct, thank you, I fixed it
